require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IconsController do

  # This should return the minimal set of attributes required to create a valid
  # Icon. As you add validations to Icon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IconsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all icons as @icons" do
      icon = Icon.create! valid_attributes
      get :index, {}, valid_session
      assigns(:icons).should eq([icon])
    end
  end

  describe "GET show" do
    it "assigns the requested icon as @icon" do
      icon = Icon.create! valid_attributes
      get :show, {:id => icon.to_param}, valid_session
      assigns(:icon).should eq(icon)
    end
  end

  describe "GET new" do
    it "assigns a new icon as @icon" do
      get :new, {}, valid_session
      assigns(:icon).should be_a_new(Icon)
    end
  end

  describe "GET edit" do
    it "assigns the requested icon as @icon" do
      icon = Icon.create! valid_attributes
      get :edit, {:id => icon.to_param}, valid_session
      assigns(:icon).should eq(icon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Icon" do
        expect {
          post :create, {:icon => valid_attributes}, valid_session
        }.to change(Icon, :count).by(1)
      end

      it "assigns a newly created icon as @icon" do
        post :create, {:icon => valid_attributes}, valid_session
        assigns(:icon).should be_a(Icon)
        assigns(:icon).should be_persisted
      end

      it "redirects to the created icon" do
        post :create, {:icon => valid_attributes}, valid_session
        response.should redirect_to(Icon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved icon as @icon" do
        # Trigger the behavior that occurs when invalid params are submitted
        Icon.any_instance.stub(:save).and_return(false)
        post :create, {:icon => { "name" => "invalid value" }}, valid_session
        assigns(:icon).should be_a_new(Icon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Icon.any_instance.stub(:save).and_return(false)
        post :create, {:icon => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested icon" do
        icon = Icon.create! valid_attributes
        # Assuming there are no other icons in the database, this
        # specifies that the Icon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Icon.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => icon.to_param, :icon => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested icon as @icon" do
        icon = Icon.create! valid_attributes
        put :update, {:id => icon.to_param, :icon => valid_attributes}, valid_session
        assigns(:icon).should eq(icon)
      end

      it "redirects to the icon" do
        icon = Icon.create! valid_attributes
        put :update, {:id => icon.to_param, :icon => valid_attributes}, valid_session
        response.should redirect_to(icon)
      end
    end

    describe "with invalid params" do
      it "assigns the icon as @icon" do
        icon = Icon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Icon.any_instance.stub(:save).and_return(false)
        put :update, {:id => icon.to_param, :icon => { "name" => "invalid value" }}, valid_session
        assigns(:icon).should eq(icon)
      end

      it "re-renders the 'edit' template" do
        icon = Icon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Icon.any_instance.stub(:save).and_return(false)
        put :update, {:id => icon.to_param, :icon => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested icon" do
      icon = Icon.create! valid_attributes
      expect {
        delete :destroy, {:id => icon.to_param}, valid_session
      }.to change(Icon, :count).by(-1)
    end

    it "redirects to the icons list" do
      icon = Icon.create! valid_attributes
      delete :destroy, {:id => icon.to_param}, valid_session
      response.should redirect_to(icons_url)
    end
  end

end
