require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectProductsController do

  # This should return the minimal set of attributes required to create a valid
  # ProjectProduct. As you add validations to ProjectProduct, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "project" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectProductsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all project_products as @project_products" do
      project_product = ProjectProduct.create! valid_attributes
      get :index, {}, valid_session
      assigns(:project_products).should eq([project_product])
    end
  end

  describe "GET show" do
    it "assigns the requested project_product as @project_product" do
      project_product = ProjectProduct.create! valid_attributes
      get :show, {:id => project_product.to_param}, valid_session
      assigns(:project_product).should eq(project_product)
    end
  end

  describe "GET new" do
    it "assigns a new project_product as @project_product" do
      get :new, {}, valid_session
      assigns(:project_product).should be_a_new(ProjectProduct)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_product as @project_product" do
      project_product = ProjectProduct.create! valid_attributes
      get :edit, {:id => project_product.to_param}, valid_session
      assigns(:project_product).should eq(project_product)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectProduct" do
        expect {
          post :create, {:project_product => valid_attributes}, valid_session
        }.to change(ProjectProduct, :count).by(1)
      end

      it "assigns a newly created project_product as @project_product" do
        post :create, {:project_product => valid_attributes}, valid_session
        assigns(:project_product).should be_a(ProjectProduct)
        assigns(:project_product).should be_persisted
      end

      it "redirects to the created project_product" do
        post :create, {:project_product => valid_attributes}, valid_session
        response.should redirect_to(ProjectProduct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_product as @project_product" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectProduct.any_instance.stub(:save).and_return(false)
        post :create, {:project_product => { "project" => "invalid value" }}, valid_session
        assigns(:project_product).should be_a_new(ProjectProduct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectProduct.any_instance.stub(:save).and_return(false)
        post :create, {:project_product => { "project" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_product" do
        project_product = ProjectProduct.create! valid_attributes
        # Assuming there are no other project_products in the database, this
        # specifies that the ProjectProduct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProjectProduct.any_instance.should_receive(:update).with({ "project" => "" })
        put :update, {:id => project_product.to_param, :project_product => { "project" => "" }}, valid_session
      end

      it "assigns the requested project_product as @project_product" do
        project_product = ProjectProduct.create! valid_attributes
        put :update, {:id => project_product.to_param, :project_product => valid_attributes}, valid_session
        assigns(:project_product).should eq(project_product)
      end

      it "redirects to the project_product" do
        project_product = ProjectProduct.create! valid_attributes
        put :update, {:id => project_product.to_param, :project_product => valid_attributes}, valid_session
        response.should redirect_to(project_product)
      end
    end

    describe "with invalid params" do
      it "assigns the project_product as @project_product" do
        project_product = ProjectProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => project_product.to_param, :project_product => { "project" => "invalid value" }}, valid_session
        assigns(:project_product).should eq(project_product)
      end

      it "re-renders the 'edit' template" do
        project_product = ProjectProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => project_product.to_param, :project_product => { "project" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_product" do
      project_product = ProjectProduct.create! valid_attributes
      expect {
        delete :destroy, {:id => project_product.to_param}, valid_session
      }.to change(ProjectProduct, :count).by(-1)
    end

    it "redirects to the project_products list" do
      project_product = ProjectProduct.create! valid_attributes
      delete :destroy, {:id => project_product.to_param}, valid_session
      response.should redirect_to(project_products_url)
    end
  end

end
