require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SurklesController do

  # This should return the minimal set of attributes required to create a valid
  # Surkle. As you add validations to Surkle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "floorplan" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurklesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all surkles as @surkles" do
      surkle = Surkle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:surkles).should eq([surkle])
    end
  end

  describe "GET show" do
    it "assigns the requested surkle as @surkle" do
      surkle = Surkle.create! valid_attributes
      get :show, {:id => surkle.to_param}, valid_session
      assigns(:surkle).should eq(surkle)
    end
  end

  describe "GET new" do
    it "assigns a new surkle as @surkle" do
      get :new, {}, valid_session
      assigns(:surkle).should be_a_new(Surkle)
    end
  end

  describe "GET edit" do
    it "assigns the requested surkle as @surkle" do
      surkle = Surkle.create! valid_attributes
      get :edit, {:id => surkle.to_param}, valid_session
      assigns(:surkle).should eq(surkle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Surkle" do
        expect {
          post :create, {:surkle => valid_attributes}, valid_session
        }.to change(Surkle, :count).by(1)
      end

      it "assigns a newly created surkle as @surkle" do
        post :create, {:surkle => valid_attributes}, valid_session
        assigns(:surkle).should be_a(Surkle)
        assigns(:surkle).should be_persisted
      end

      it "redirects to the created surkle" do
        post :create, {:surkle => valid_attributes}, valid_session
        response.should redirect_to(Surkle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved surkle as @surkle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Surkle.any_instance.stub(:save).and_return(false)
        post :create, {:surkle => { "floorplan" => "invalid value" }}, valid_session
        assigns(:surkle).should be_a_new(Surkle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Surkle.any_instance.stub(:save).and_return(false)
        post :create, {:surkle => { "floorplan" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested surkle" do
        surkle = Surkle.create! valid_attributes
        # Assuming there are no other surkles in the database, this
        # specifies that the Surkle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Surkle.any_instance.should_receive(:update).with({ "floorplan" => "MyText" })
        put :update, {:id => surkle.to_param, :surkle => { "floorplan" => "MyText" }}, valid_session
      end

      it "assigns the requested surkle as @surkle" do
        surkle = Surkle.create! valid_attributes
        put :update, {:id => surkle.to_param, :surkle => valid_attributes}, valid_session
        assigns(:surkle).should eq(surkle)
      end

      it "redirects to the surkle" do
        surkle = Surkle.create! valid_attributes
        put :update, {:id => surkle.to_param, :surkle => valid_attributes}, valid_session
        response.should redirect_to(surkle)
      end
    end

    describe "with invalid params" do
      it "assigns the surkle as @surkle" do
        surkle = Surkle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Surkle.any_instance.stub(:save).and_return(false)
        put :update, {:id => surkle.to_param, :surkle => { "floorplan" => "invalid value" }}, valid_session
        assigns(:surkle).should eq(surkle)
      end

      it "re-renders the 'edit' template" do
        surkle = Surkle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Surkle.any_instance.stub(:save).and_return(false)
        put :update, {:id => surkle.to_param, :surkle => { "floorplan" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested surkle" do
      surkle = Surkle.create! valid_attributes
      expect {
        delete :destroy, {:id => surkle.to_param}, valid_session
      }.to change(Surkle, :count).by(-1)
    end

    it "redirects to the surkles list" do
      surkle = Surkle.create! valid_attributes
      delete :destroy, {:id => surkle.to_param}, valid_session
      response.should redirect_to(surkles_url)
    end
  end

end
